name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fakedatabase.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Linting
        run: npm run lint

      -name: Print Environment Variable
        run: echo $MY_ENV_VAR